### ISSUE TITLE
Go1.11 travis failed

### ISSUE THREAD

**Issue by simukti** [simukti/sqldb-logger#12]
```yaml
language: go
sudo: false
install: true
go_import_path: github.com/simukti/sqldb-logger

go:
  - "1.11"
  - "1.12"
  - "1.13"
  - master

env:
  global:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on

allow_failures:
  - master

branches:
  only:
    - master

before_install:
  - go get github.com/mattn/goveralls
  - go mod download || true
  - go mod vendor -v

script:
  - go vet
  - test -z "$(go fmt ./...)" # fail if not formatted properly
  - go test -mod=vendor -v -race -coverprofile=coverage.out -covermode=atomic -tags=unit ./...

after_success:
  - $GOPATH/bin/goveralls -v -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
  - bash <(curl -s https://codecov.io/bash)
```

**ERROR**

```
$ go test -mod=vendor -v -race -coverprofile=coverage.out -covermode=atomic -tags=unit ./...

go build github.com/simukti/sqldb-logger: module requires Go 1.13

FAIL	github.com/simukti/sqldb-logger [build failed]

go build github.com/simukti/sqldb-logger: module requires Go 1.13

FAIL	github.com/simukti/sqldb-logger/logadapter/onelogadapter [build failed]

FAIL	github.com/simukti/sqldb-logger/logadapter/zapadapter [build failed]

FAIL	github.com/simukti/sqldb-logger/logadapter/zerologadapter [build failed]

The command "go test -mod=vendor -v -race -coverprofile=coverage.out -covermode=atomic -tags=unit ./..." exited with 1.
```
